import os

from platform_runtime import (
    default_adb_bin,
    default_bluestacks_app_name,
    default_bluestacks_process_name,
)

def _load_env_file():
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    if not os.path.exists(env_path):
        return

    try:
        with open(env_path, 'r', encoding='utf-8') as env_file:
            for raw_line in env_file:
                line = raw_line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = value
    except OSError:
        return

_load_env_file()

START_DELAY_SECONDS = 5
STORAGE_CHECK_LIMIT = 20000
TELEGRAM_UI_MODE = os.getenv('TELEGRAM_UI_MODE', 'default').strip().lower() or 'default'

INPUT_PROFILE_DEFAULT = 'default'
ADB_INPUT_BIN = default_adb_bin()
ADB_DEVICE_SERIAL = ''
ADB_CMD_TIMEOUT_SECONDS = 5.0
ADB_SCREENCAP_TIMEOUT_SECONDS = 4.0
ADB_SCREEN_SIZE = (1920, 1080)
ADB_CONNECT_PORTS = '5555 5556 5565 5575 5585'
BLUESTACKS_APP_NAME = default_bluestacks_app_name()
BLUESTACKS_PROCESS_NAME = default_bluestacks_process_name()
COC_PACKAGE_NAME = 'com.supercell.clashofclans'

ENABLE_AUTO_RECOVERY = True
RECOVERY_ERROR_IMAGE_GLOB = 'images/errs_bg/*.png'
RECOVERY_ERROR_CONFIDENCE = 0.87
RECOVERY_ERROR_REGION = None
RECOVERY_BLACK_SCREEN_ENABLED = True
RECOVERY_BLACK_SCREEN_REGION = None
RECOVERY_BLACK_SCREEN_BRIGHTNESS_MAX = 12.0
RECOVERY_BLACK_SCREEN_MIN_COVERAGE = 0.92
RECOVERY_TELEGRAM_DELETE_AFTER_SECONDS = 10
RECOVERY_GUARD_MAX_CHECKS = 25
RECOVERY_MAX_LOOP_SECONDS = 240.0
RECOVERY_NO_PROGRESS_SECONDS = 120.0
RECOVERY_STALE_SCREEN_SECONDS = 80.0
RECOVERY_STALE_SAMPLE_INTERVAL_SECONDS = 5.0
RECOVERY_STALE_REGION = None
RECOVERY_RATE_WINDOW_SECONDS = 3600.0
RECOVERY_MAX_ATTEMPTS_PER_WINDOW = 6
RECOVERY_ADB_DEVICE_TIMEOUT_SECONDS = 40.0
RECOVERY_POST_LAUNCH_SLEEP_SECONDS = 8.0
RECOVERY_EMULATOR_RESTART_WAIT_SECONDS = 12.0
RECOVERY_TELEGRAM_NOTIFY = True
RECOVERY_RESTART_BOT_PROCESS = True

WAIT_FOR_IMAGE_TIMEOUT_SECONDS = 75.0

ENABLE_STORAGE_OCR_STOP = False
STORAGE_OCR_REGION = (1147, 103, 307, 139)
STORAGE_OCR_GOLD_SUBREGION = (1154, 109, 236, 48)
STORAGE_OCR_ELIXIR_SUBREGION = (1154, 187, 236, 47)
STORAGE_OCR_FULL_THRESHOLD = 28500000
STORAGE_OCR_RETRY_FRAMES = 3
STORAGE_OCR_PSM_MODES = (7, 6, 13)
STORAGE_OCR_MESSAGE = '🏦 Вождь! Хранилища полны: золото и эликсир переполнены. Пора прокачивать объекты! ⚒️'
ENABLE_STORAGE_MONITOR = True
STORAGE_MONITOR_EVERY_ATTACKS = 20
STORAGE_MONITOR_THRESHOLD = 29000000
STORAGE_MONITOR_GOLD_REGION = (1145, 104, 316, 47)
STORAGE_MONITOR_ELIXIR_REGION = (1145, 180, 313, 48)
STORAGE_MONITOR_GOLD_INNER_CROP = (18, 2, 10, 2)
STORAGE_MONITOR_ELIXIR_INNER_CROP = (18, 2, 10, 2)
ENABLE_WALL_KEY_CYCLE = True
WALL_KEY_CYCLE_EVERY_ATTACKS = 20
WALL_KEY_CYCLE_KEY = '-'
WALL_KEY_CYCLE_DURATION_SECONDS = 95.0

ACCOUNT_SWITCH_CURRENT_ACCOUNT_REGION = (150, 90, 170, 30)
ACCOUNT_SWITCH_LIST_REGION = (1020, 470, 435, 425)
ACCOUNT_SWITCH_LIST_REGION_AFTER_SCROLL = (1020, 465, 435, 360)
ACCOUNT_SWITCH_DETECT_CONFIDENCE = 0.82
ACCOUNT_SWITCH_LIST_CONFIDENCE = 0.80
ACCOUNT_SWITCH_OPEN_MENU_KEY = '0'
ACCOUNT_SWITCH_OPEN_MENU_SLEEP = 0.3
ACCOUNT_SWITCH_OPEN_LIST_KEY = '9'
ACCOUNT_SWITCH_AFTER_OPEN_LIST_SLEEP = 1.0
ACCOUNT_SWITCH_RETURN_HOME_KEY = 'h'
ACCOUNT_SWITCH_RETURN_HOME_PRESS_SLEEP = 1.2
ACCOUNT_SWITCH_HOME_TIMEOUT_SECONDS = 20.0
ACCOUNT_SWITCH_CONFIRM_HOME_TIMEOUT_SECONDS = 25.0
ACCOUNT_SWITCH_SCROLL_DURATION = 0.35
ACCOUNT_SWITCH_AFTER_SCROLL_SLEEP = 0.7
ACCOUNT_SWITCH_AFTER_CLICK_SLEEP = 3.0
ACCOUNT_SWITCH_MAX_SCROLLS = 6
ACCOUNT_SWITCH_COORDINATE_JITTER_PX = 8
ACCOUNT_SWITCH_CLICK_POINTS = {
    'proxima': (1250, 550),
    'old_proxima': (1275, 660),
    'yung_proxima': (1300, 780),
    'samgold': (1290, 865),
}
FILL_STORAGES_ACCOUNT_SEQUENCE = (
    'proxima',
    'old_proxima',
    'yung_proxima',
    'samgold',
)
FILL_STORAGES_ATTACKS_PER_ACCOUNT = 21
FILL_STORAGES_POLL_INTERVAL_SECONDS = 2.0

ENABLE_BATTLE_GOLD_FILTER = True
BATTLE_GOLD_REGION = (35, 190, 170, 45)
BATTLE_ELIXIR_REGION = (27, 235, 174, 39)
BATTLE_GOLD_INNER_CROP = (18, 2, 8, 2)
BATTLE_ELIXIR_INNER_CROP = (18, 2, 8, 2)
BATTLE_GOLD_REGION_FALLBACKS = (
    (29, 188, 205, 52),
    (24, 186, 220, 56),
)
BATTLE_ELIXIR_REGION_FALLBACKS = (
    (21, 233, 210, 46),
    (18, 231, 225, 50),
)
BATTLE_GOLD_MIN = 500000
BATTLE_ELIXIR_MIN = 500000
BATTLE_GOLD_MAX = 10000000
BATTLE_GOLD_UNRELIABLE_BELOW = 50000
BATTLE_GOLD_REROLL_KEY = 'enter'
BATTLE_GOLD_REROLL_SLEEP = 0.8
BATTLE_GOLD_OCR_MAX_REROLLS = 200
BATTLE_GOLD_OCR_RETRY_FRAMES = 4
BATTLE_GOLD_OCR_QUICK_FRAMES = 1
BATTLE_GOLD_OCR_PSM_MODES = (7, 6, 13)
BATTLE_GOLD_OCR_STRICT_DIGITS = 6
BATTLE_GOLD_OCR_ACCEPT_MARGIN = 50000
BATTLE_GOLD_ACCEPT_ON_UNKNOWN = False
BATTLE_GOLD_TEMPLATE_DIR = '.digit_templates/battle_loot_v2'
BATTLE_GOLD_TEMPLATE_MIN_DIGITS = 6
BATTLE_GOLD_TEMPLATE_MAX_DIGITS = 7
BATTLE_GOLD_TEMPLATE_SCORE_THRESHOLD = 0.56
BATTLE_GOLD_TEMPLATE_QUICK_FRAMES = 1
BATTLE_GOLD_TEMPLATE_RETRY_FRAMES = 4
BATTLE_GOLD_TEMPLATE_BOOTSTRAP_ENABLED = True
BATTLE_GOLD_USE_TEMPLATE_FALLBACK = True
BATTLE_GOLD_TEMPLATE_SAVE_LIMIT_PER_DIGIT = 12
BATTLE_RESOURCE_DEBUG_LOG = True
BATTLE_RESOURCE_DEBUG_SAVE_BAD_READS = True
BATTLE_RESOURCE_DEBUG_DIR = 'debug/battle_loot'

BOT_MODE_DEFAULT = 'default'

ENABLE_SEARCH_BUTTON_GUARD = True
SEARCH_BUTTON_IMAGE_PATH = 'images/here/button_search.png'
SEARCH_BUTTON_IMAGE_PATHS = [
    'images/here/*.png',
]
IMAGE_MATCH_CONFIDENCE = 0.88
ENABLE_CV2_TEMPLATE_FALLBACK = False
CV2_TEMPLATE_CONFIDENCE_DELTA = 0.05
CV2_TEMPLATE_SCALES = (1.0, 0.95, 1.05, 0.9, 1.1, 0.85, 1.15, 0.8, 1.2)
SEARCH_BUTTON_CHECK_INTERVAL_SECONDS = 0.5
SEARCH_BUTTON_LOG_EVERY_SECONDS = 15
SEARCH_BUTTON_SEARCH_REGION = None

ENABLE_ARMY_READY_GUARD = True
ARMY_READY_IMAGE_PATH = 'images/on_war/army_ready.png'
ARMY_READY_IMAGE_PATHS = [
    'images/on_war/*.png',
]
ARMY_READY_CHECK_INTERVAL_SECONDS = 0.5
ARMY_READY_LOG_EVERY_SECONDS = 15
ARMY_READY_SEARCH_REGION = None

ENABLE_GO_HOME_GUARD = True
GO_HOME_IMAGE_PATH = 'images/go_home.png'
GO_HOME_IMAGE_PATHS = [
    'images/go_home*.png',
]
GO_HOME_CHECK_INTERVAL_SECONDS = 0.5
GO_HOME_LOG_EVERY_SECONDS = 15
GO_HOME_SEARCH_REGION = None

ENABLE_OKAY_AFTER_BATTLE = True
OKAY_AFTER_BATTLE_IMAGE_PATH = 'images/okay.png'
OKAY_AFTER_BATTLE_IMAGE_PATHS = [
    'images/okay*.png',
]
OKAY_AFTER_BATTLE_SEARCH_REGION = None
OKAY_AFTER_BATTLE_CHECK_SECONDS = 4.0
OKAY_AFTER_BATTLE_POLL_INTERVAL_SECONDS = 0.4
OKAY_AFTER_BATTLE_KEY = '='

SEARCH_SEQUENCE = [
    ('space', 0.6),
    ('e', 0.6),
    ('i', 1.2),
]

ENABLE_CLAN_CAKE = False

ALIGN_ZOOM_KEY = 'down'
ALIGN_ZOOM_DURATION = 1.2  # seconds to hold zoom key
ALIGN_KEYS = [
    ('s', 0.6),
    ('d', 0.6),
]
HOME_ALIGN_KEYS = [
    ('w', 0.6),
    ('a', 0.6),
]

TROOP_SELECT_KEYS = ['1', '2']
TROOP_SELECT_SLEEP = 0.8

DEPLOY_KEY = 'g'
DEPLOY_COUNT = 12
DEPLOY_COUNT_BY_TROOP_KEY = {'1': 9, '2': 5}
DEPLOY_INTERVAL = 0.1

HERO_KEYS = ['4', '5', '6', '7']
HERO_DEPLOY_KEY = 'g'
HERO_DEPLOY_SLEEP = 0.2
HERO_ABILITY_SLEEP = 0.3
HERO_ABILITY_PRESS_KEY = HERO_DEPLOY_KEY
HERO_ABILITY_DELAY_BY_KEY = {
    '4': 1.0,
    '5': 7.0,
    '6': 3.0,
    '7': 2.0,
}

BATTLE_MACHINE_KEY = '3'
BATTLE_MACHINE_DEPLOY_SLEEP = 0.3

SPELL_SELECT_KEYS = ['8']
SPELL_SELECT_SLEEP = 0.3
SPELL_MODE_DEFAULT = 'stoneDick'
SPELL_COUNT = 11
SPELL_AREA = {
    'x_min_frac': 0.44,
    'x_max_frac': 0.52,
    'y_min_frac': 0.25,
    'y_max_frac': 0.50,
}
SPELL_INTERVAL = 1.0
SPELL_MAP_POINTS = [
    {'x_frac': 0.20, 'y_frac': 0.20},
    {'x_frac': 0.36, 'y_frac': 0.18},
    {'x_frac': 0.52, 'y_frac': 0.22},
    {'x_frac': 0.68, 'y_frac': 0.20},
    {'x_frac': 0.82, 'y_frac': 0.24},
    {'x_frac': 0.28, 'y_frac': 0.42},
    {'x_frac': 0.46, 'y_frac': 0.40},
    {'x_frac': 0.64, 'y_frac': 0.44},
    {'x_frac': 0.24, 'y_frac': 0.66},
    {'x_frac': 0.50, 'y_frac': 0.68},
    {'x_frac': 0.76, 'y_frac': 0.64},
]
SPELL_POINT_JITTER_X_PX = 30
SPELL_POINT_JITTER_Y_PX = 26
SPELL_CRAZYWALLS_CENTER = {
    'x_frac': 0.50,
    'y_frac': 0.38,
}
SPELL_CRAZYWALLS_OFFSET_PX = 40
SPELL_CRAZYWALLS_TOTAL_SECONDS = 2.0
SPELL_CRAZYWALLS_CAST_PATTERN = (0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3)
SURRENDER_WAIT = 28
SURRENDER_SEQUENCE = [
    ('e', 1),  # open surrender
    ('o', 1),  # confirm
    ('h', 3),  # return home
]

ENABLE_BATTLE_SCREENSHOTS = True
SAVE_BATTLE_SCREENSHOTS_LOCAL = False
BATTLE_SCREENSHOT_DIR = 'screenshots'
BATTLE_SCREENSHOT_FORMAT = 'JPEG'
BATTLE_SCREENSHOT_JPEG_QUALITY = 50
BATTLE_REPORT_EVERY = 0

ENABLE_TELEGRAM_REPORTS = True
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '').strip()
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '').strip()
_telegram_allowed_chat_ids_env = os.getenv('TELEGRAM_ALLOWED_CHAT_IDS', '').strip()
TELEGRAM_ALLOWED_CHAT_IDS = tuple(
    chat_id
    for chat_id in dict.fromkeys(
        [
            TELEGRAM_CHAT_ID,
            '5522146122',
            '2124413020',
            *[
                item.strip()
                for item in _telegram_allowed_chat_ids_env.split(',')
                if item.strip()
            ],
        ]
    )
    if chat_id
)
TELEGRAM_SEND_TIMEOUT_SECONDS = 10
TELEGRAM_SEND_RETRIES = 1
  
TELEGRAM_CONTROL_POLL_TIMEOUT_SECONDS = 20
TELEGRAM_CONTROL_POLL_INTERVAL_SECONDS = 1
