import os

BOT2_CONFIDENCE = 0.88
BOT2_START_DELAY_SECONDS = 5.0
BOT2_LOOP_SLEEP = 0.35
BOT2_ATTACK_COOLDOWN_SECONDS = 2.0
BOT2_SEARCH_STEP_DELAY = 0.25
BOT2_ATTACK_ZOOM_SECONDS = 2.0
BOT2_MACHINE_DELAY = 0.3
BOT2_DEPLOY_DELAY = 0.1
BOT2_SEARCH_RETRY_SECONDS = 4.0
BOT2_AFTER_H_COOLDOWN = 2.5
BOT2_AFTER_DASH_COOLDOWN = 2.5
BOT2_SWEEP_2_9_MIN_SECONDS = 1.0
BOT2_SWEEP_2_9_MAX_SECONDS = 5.0
BOT2_PRESS_1_MIN_SECONDS = 4.0
BOT2_PRESS_1_MAX_SECONDS = 6.0
BOT2_SWEEP_2_9_G_MIN_SECONDS = 40.0
BOT2_SWEEP_2_9_G_MAX_SECONDS = 50.0
BOT2_BASE_MACRO_EVERY_ATTACKS = 10
BOT2_BASE_MACRO_D_HOLD = 0.5
BOT2_BASE_MACRO_W_HOLD = 0.3
BOT2_BASE_MACRO_AFTER_MOVE_SLEEP = 0.3
BOT2_BASE_MACRO_AFTER_L_SLEEP = 0.5

BOT2_IMAGES_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images', 'bot2')
BOT2_HOME_IMAGES = (
    'home_1.png',
    'home_11.png',
    'home_12.png',
    'home_13.png',
    'home_14.png',
)
BOT2_ATTACK_READY_IMAGES = (
    'attack_ready_3.png',
    'attack_ready_4.png',
    'attack_ready_5.png',
)
BOT2_RETURN_HOME_IMAGE = 'battle_return_home.png'
BOT2_STAR_BONUS_IMAGE = 'battle_star_bonus.png'
BOT2_NOT_LOOT_IMAGES = ('not_loot.png', 'not_loot1.png')
BOT2_NOT_LOOT_CHECK_EVERY_ATTACKS = 10
BOT2_NOT_LOOT_CLOSE_X_PRESSES = 4
BOT2_NOT_LOOT_CLOSE_X_SLEEP = 0.15
